-- 建立資料庫與資料表
CREATE DATABASE IF NOT EXISTS seatDB
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE seatDB;

CREATE TABLE IF NOT EXISTS SeatingChart (
    FLOOR_SEAT_SEQ INT AUTO_INCREMENT PRIMARY KEY,
    FLOOR_NO INT NOT NULL,
    SEAT_NO VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS Employee (
    EMP_ID CHAR(5) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    FLOOR_SEAT_SEQ INT,
    FOREIGN KEY (FLOOR_SEAT_SEQ) REFERENCES SeatingChart(FLOOR_SEAT_SEQ)
);
